name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: workind_dir
      run: cd 3105
    - name: dircheck
      run: ls
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Run Code
      run: ./main 
